#!/usr/bin/env python3
"""Single Gemini call extracts a transaction line from one receipt.

Started as the M4 spike (no response_schema, free-form JSON, hand-inspected).
M5.2 wired in `generated/response_schema_meal.json` so structural correctness
is enforced by the SDK rather than the prompt.

Auth uses Application Default Credentials (ADC). Works on Cloud Run
automatically via the metadata server. Locally, run once:
    gcloud auth application-default login
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


DEFAULT_MODEL = "gemini-3-flash-preview"
DEFAULT_LOCATION = "global"


RESPONSE_SCHEMA_PATH = (
    Path(__file__).resolve().parent.parent / "generated" / "response_schema_meal.json"
)


PROMPT = """You are extracting a single meal transaction line from a receipt
for a Stanford expense report. The receipt is attached as an image.

Return a JSON array containing one transaction line object. Its shape is
enforced by the response schema — fill the values from the receipt.

# Reasoning rules

`expense_type`:
- Use `business_meal` for a meal the payee took with one or more guests.
- Use `group_travel_meal` ONLY when the receipt clearly indicates multiple
  Stanford travelers — multiple guests/diners is NOT a group_travel signal.
- Alcohol presence is NOT encoded in `expense_type`. Use the dedicated
  `has_alcohol_on_receipt` boolean (and `alcohol_amount` for the dollar
  total). The workbench will assemble "Business Meal with Alcohol" or
  "Group Travel Meal with Alcohol" from those two fields when displaying.
- Sales tax labels like GST, VAT, HST, and "Sales Tax" are tax categories,
  NOT expense_type signals.

`tip_amount`:
- Look below the subtotal/tax block. Common labels: `Tip`, `Gratuity`,
  `Service Charge`. The tip can be handwritten in or printed.
- If `Total > Subtotal + Tax`, the difference is likely tip even when not
  explicitly labeled — use `medium` confidence in that case.
- If the receipt has space for a tip but you can't read the value, use
  `value: null` with `low` confidence and `needs_review: true`.

`original_currency` and `original_amount`:
- For USD receipts (i.e., the printed amounts are in dollars), set BOTH to
  null with `kind: system_generated, origin: not_applicable_for_domestic`.
- Only fill them when the receipt's printed amounts are in a non-USD
  currency. `original_amount` is the amount as printed on the receipt in
  that currency; `line_amount_usd` is the converted USD amount.

`country_of_activity`:
- Fill from the merchant address when present (city/state/country gives the
  country). Pass 2 will null this for domestic expenses if needed.

`extras.merchant_address`:
- The full printed merchant address (street + city + region + country, if
  any are visible). This is the raw text; reduction parses it later.

`extras.printed_currency`:
- The currency literally on the receipt. ISO 4217 code if you see one
  (e.g. `USD`, `SGD`, `EUR`). Otherwise infer from a printed symbol
  (`$` alone is most likely USD; £ is GBP; € is EUR; ¥ is JPY/CNY —
  use medium confidence and let reduction disambiguate).

`has_alcohol_on_receipt` and `alcohol_amount`:
- `has_alcohol_on_receipt` is true if ANY line item is alcohol (cocktail,
  beer, wine, etc.), even if the price is zero ("on the house").
- `alcohol_amount` is the SUM of all alcohol line item prices. Use 0.0 when
  alcohol is on the receipt but free; null when no alcohol is present.

# _meta convention

- `confidence` is ordinal: `low` when guessing, `medium` when ambiguous but
  defensible, `high` when unambiguous on the receipt. NOT a probability.
- `evidence` for present values: `kind: document_span` with `filename`,
  `page`, and an exact `quote` from the receipt.
- `evidence` for null values: `kind: system_generated` with one of
  `origin: not_present_in_receipt`, `not_applicable_for_domestic`, or
  `not_applicable_for_foreign`. Do NOT cite an unrelated quote with
  `document_span` to evidence a null value.
- `needs_review` is true for any value you guessed, and any field where
  you used `medium` or `low` confidence.
- `flags` stays empty unless you observe something irregular.
"""


def load_response_schema():
    """Load the meal response_schema generated by generate_response_schema.py."""
    from google.genai import types

    schema_dict = json.loads(RESPONSE_SCHEMA_PATH.read_text())
    return types.Schema.model_validate(schema_dict)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument(
        "--project",
        default=os.environ.get("VERTEX_PROJECT_ID"),
        help="GCP project (defaults to $VERTEX_PROJECT_ID; Cloud Run sets it "
        "via --set-env-vars in deploy/cloudbuild.yaml).",
    )
    parser.add_argument(
        "--location",
        default=os.environ.get("VERTEX_LOCATION", DEFAULT_LOCATION),
    )
    parser.add_argument(
        "--model",
        default=os.environ.get("VERTEX_GEMINI_MODEL", DEFAULT_MODEL),
    )
    return parser.parse_args()


def detect_mime_type(path: Path) -> str:
    suffix = path.suffix.lower()
    return {
        ".pdf": "application/pdf",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
    }.get(suffix) or sys.exit(f"unsupported image format: {suffix}")


def main() -> int:
    args = parse_args()

    if not args.image.exists():
        sys.exit(f"image not found: {args.image}")

    from google import genai
    from google.genai import types

    if not args.project:
        sys.exit(
            "project required: pass --project or set $VERTEX_PROJECT_ID. "
            "Cloud Run gets this from --set-env-vars in deploy/cloudbuild.yaml."
        )

    # Application Default Credentials: works on Cloud Run via the metadata
    # server, and locally after `gcloud auth application-default login`.
    # The SDK picks credentials up automatically when none are passed.
    client = genai.Client(
        vertexai=True, project=args.project, location=args.location
    )

    image_bytes = args.image.read_bytes()
    mime = detect_mime_type(args.image)

    response_schema = load_response_schema()

    response = client.models.generate_content(
        model=args.model,
        contents=[
            f"Filename: {args.image.name}\n\n{PROMPT}",
            types.Part.from_bytes(data=image_bytes, mime_type=mime),
        ],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=response_schema,
            # Gemini 3 includes "thinking" tokens in this budget. Tamarine
            # spent 7860 thinking tokens; 8192 is too small. Be generous.
            max_output_tokens=32768,
            temperature=0.0,
        ),
    )

    raw_text = response.text or ""
    args.output.parent.mkdir(parents=True, exist_ok=True)

    try:
        parsed = json.loads(raw_text)
    except json.JSONDecodeError as err:
        raw_path = args.output.with_suffix(args.output.suffix + ".raw.txt")
        err_path = args.output.with_suffix(args.output.suffix + ".error.txt")
        raw_path.write_text(raw_text)
        diag = {
            "json_decode_error": str(err),
            "raw_text_length": len(raw_text),
            "candidates": [
                {
                    "finish_reason": str(getattr(c, "finish_reason", None)),
                    "safety_ratings": [str(r) for r in (getattr(c, "safety_ratings", None) or [])],
                    "content_parts": len((getattr(c, "content", None) and c.content.parts) or []),
                }
                for c in (getattr(response, "candidates", None) or [])
            ],
            "prompt_feedback": str(getattr(response, "prompt_feedback", None)),
            "usage_metadata": str(getattr(response, "usage_metadata", None)),
        }
        err_path.write_text(json.dumps(diag, indent=2))
        print(f"FAILED to parse JSON. Raw -> {raw_path}, diag -> {err_path}", file=sys.stderr)
        return 1

    # Inject source_filename — system context, not extracted by Gemini.
    # Reduction reads this to populate ExpenseReport.transaction_lines[]
    # .common.source_document.filename.
    if isinstance(parsed, list):
        for entry in parsed:
            if isinstance(entry, dict):
                entry["source_filename"] = args.image.name
    elif isinstance(parsed, dict):
        parsed["source_filename"] = args.image.name

    args.output.write_text(json.dumps(parsed, indent=2, ensure_ascii=False))
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
