#!/usr/bin/env python3
"""Single Gemini call extracts a transaction line from one receipt.

Started as the M4 spike (no response_schema, free-form JSON, hand-inspected).
M5.2 wired in `generated/response_schema_meal.json` so structural correctness
is enforced by the SDK rather than the prompt.

Auth mirrors scripts/transcribe_with_google_genai.py — service-account key
either via --service-account-key or VERTEX_SERVICE_ACCOUNT_KEY.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path


CLOUD_PLATFORM_SCOPE = "https://www.googleapis.com/auth/cloud-platform"
DEFAULT_MODEL = "gemini-3-flash-preview"
DEFAULT_LOCATION = "global"


RESPONSE_SCHEMA_PATH = (
    Path(__file__).resolve().parent.parent / "generated" / "response_schema_meal.json"
)


PROMPT = """You are extracting a single meal transaction line from a receipt
for a Stanford expense report. The receipt is attached as an image.

Return a JSON array containing one transaction line object. Its shape is
enforced by the response schema — fill the values from the receipt.

For every leaf, the `_meta` block carries provenance:
- `confidence` is ordinal (high/medium/low), NOT a probability.
- `evidence` is one or more pointers. For values present on the receipt, use
  `kind: document_span` with `filename`, `page`, and `quote` (the exact text
  from the receipt). For values you cannot determine from the receipt, use
  `kind: system_generated` with `origin: not_present_in_receipt`.
- `needs_review` is true when the FA must look at this field. Set true for
  `attendees`, `meal_purpose`, and any value you had to guess.
- `flags` is an empty array unless you observe something irregular.
"""


def load_response_schema():
    """Load the meal response_schema generated by generate_response_schema.py."""
    from google.genai import types

    schema_dict = json.loads(RESPONSE_SCHEMA_PATH.read_text())
    return types.Schema.model_validate(schema_dict)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument(
        "--service-account-key",
        type=Path,
        default=os.environ.get("VERTEX_SERVICE_ACCOUNT_KEY"),
        help="Service account key path (defaults to $VERTEX_SERVICE_ACCOUNT_KEY).",
    )
    parser.add_argument(
        "--project",
        default=os.environ.get("VERTEX_PROJECT_ID"),
        help="GCP project (defaults to $VERTEX_PROJECT_ID or the key's project_id).",
    )
    parser.add_argument(
        "--location",
        default=os.environ.get("VERTEX_LOCATION", DEFAULT_LOCATION),
    )
    parser.add_argument(
        "--model",
        default=os.environ.get("VERTEX_GEMINI_MODEL", DEFAULT_MODEL),
    )
    return parser.parse_args()


def detect_mime_type(path: Path) -> str:
    suffix = path.suffix.lower()
    return {
        ".pdf": "application/pdf",
        ".png": "image/png",
        ".jpg": "image/jpeg",
        ".jpeg": "image/jpeg",
    }.get(suffix) or sys.exit(f"unsupported image format: {suffix}")


def main() -> int:
    args = parse_args()

    if not args.image.exists():
        sys.exit(f"image not found: {args.image}")
    if args.service_account_key is None or not Path(args.service_account_key).exists():
        sys.exit("service account key required (--service-account-key or VERTEX_SERVICE_ACCOUNT_KEY)")

    from google import genai
    from google.genai import types
    from google.oauth2 import service_account

    key_path = Path(args.service_account_key)
    project = args.project or json.loads(key_path.read_text()).get("project_id")
    if not project:
        sys.exit("project required (--project or project_id in the key)")

    credentials = service_account.Credentials.from_service_account_file(
        str(key_path), scopes=[CLOUD_PLATFORM_SCOPE]
    )
    client = genai.Client(
        vertexai=True, project=project, location=args.location, credentials=credentials
    )

    image_bytes = args.image.read_bytes()
    mime = detect_mime_type(args.image)

    response_schema = load_response_schema()

    response = client.models.generate_content(
        model=args.model,
        contents=[
            f"Filename: {args.image.name}\n\n{PROMPT}",
            types.Part.from_bytes(data=image_bytes, mime_type=mime),
        ],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=response_schema,
            # Gemini 3 includes "thinking" tokens in this budget. Tamarine
            # spent 7860 thinking tokens; 8192 is too small. Be generous.
            max_output_tokens=32768,
            temperature=0.0,
        ),
    )

    raw_text = response.text or ""
    args.output.parent.mkdir(parents=True, exist_ok=True)

    try:
        parsed = json.loads(raw_text)
    except json.JSONDecodeError as err:
        raw_path = args.output.with_suffix(args.output.suffix + ".raw.txt")
        err_path = args.output.with_suffix(args.output.suffix + ".error.txt")
        raw_path.write_text(raw_text)
        diag = {
            "json_decode_error": str(err),
            "raw_text_length": len(raw_text),
            "candidates": [
                {
                    "finish_reason": str(getattr(c, "finish_reason", None)),
                    "safety_ratings": [str(r) for r in (getattr(c, "safety_ratings", None) or [])],
                    "content_parts": len((getattr(c, "content", None) and c.content.parts) or []),
                }
                for c in (getattr(response, "candidates", None) or [])
            ],
            "prompt_feedback": str(getattr(response, "prompt_feedback", None)),
            "usage_metadata": str(getattr(response, "usage_metadata", None)),
        }
        err_path.write_text(json.dumps(diag, indent=2))
        print(f"FAILED to parse JSON. Raw -> {raw_path}, diag -> {err_path}", file=sys.stderr)
        return 1

    args.output.write_text(json.dumps(parsed, indent=2, ensure_ascii=False))
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
